services:
  client-coursera:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client-coursera
    ports:
      - "80:5173"
    networks:
      - default
    env_file: "./client/.env"
    environment:
      - NODE_ENV=production
      - VITE_ALLOWED_HOST=coursera.zapto.org
    depends_on:
      - server-coursera
    restart: always

  server-coursera:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server-coursera
    ports:
      - "3000:3000"
      - "5001:5001"
    networks:
      - default
    environment:
      - NODE_ENV=production
    restart: always

networks:
  default:
    driver: bridge
