version: '3.8'

services:
  redis:
    image: redis:alpine
    container_name: redis-cache
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD:-Redis@123456!}
    restart: unless-stopped
    networks:
      - app-network

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql_container
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "password123@"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
      MSSQL_CONFIG_CONNECTIVITY: "LOCAL"
    volumes:
      - mssql-data:/var/opt/mssql
      - ./mssql:/mssql
    restart: always
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: chatdb
    ports:
      - "27017:27017"
    # volumes:
    #   - mongodb_data:/data/db
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  redis-data:
    driver: local
  mssql-data:
    driver: local
  # mongodb_data:
  #   driver: local




