version: '3.8'

services:
  # Prometheus
  prometheus:
    image: prom/prometheus:latest
    # volumes:
    #   - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    #   - prometheus-data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - monitoring

  # Grafana
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"  
    # volumes:
    #   - grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin 
    depends_on:
      - prometheus
    networks:
      - monitoring

# volumes:
#   prometheus-data:
#   grafana-data:

networks:
  monitoring:
    driver: bridge