services:
  client-coursera:
    build:
      context: ./client
      dockerfile: Dockerfile
      # Không cần args vì sẽ dùng file .env trong context
    container_name: client-coursera
    ports:
      - "81:5173"
    networks:
      - default
    env_file: "./client/.env"
    environment:
      - NODE_ENV=production
      - PORT=81
    depends_on:
      - server-coursera
    restart: always

  server-coursera:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server-coursera
    ports:
      - "3000:3000"
      - "5001:5001"
    networks:
      - default
    environment:
      - NODE_ENV=production
    restart: always


networks:
  default:
    driver: bridge


