version: '3.9'

services:
  nginx-load-balancer:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx-load-balancer
    ports:
      - "80:80"
    # Không sử dụng volume, mọi thứ sẽ được lưu trong container
    restart: always
    networks:
      - nginx-network
      - default

networks:
  nginx-network:
    driver: bridge
  default:
    external: true
    name: cnpm_default