version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-rust-app
    env_file:
      - .env
    ports:
      - "5010:5010" 
    restart: always