name: Notify on Production Push

on:
  push:
    branches:
      - production  # Chạy khi push lên nhánh production

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Send Email Notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{ secrets.EMAIL_USERNAME }}  # Gmail gửi thông báo
          password: ${{ secrets.EMAIL_PASSWORD }}  # App Password của Gmail gửi thông báo
          subject: "🚀 Code Pushed to Production"
          body: "Mã nguồn đã được cập nhật trên production.\nChi tiết commit: ${{ github.event.head_commit.message }}"
          to: "nguyen.vu.hung309@gmail.com,tbnguyen21@vp.fitus.edu.vn,nguyenducnha1304@gmail.com,lehoangdaian@gmail.com,khanhtiensinh297@gmail.com"
          from: "GitHub Actions <nnkhanh21@vp.fitus.edu.vn>"
