name: Notify Team on Push to Dev

on:
  push:
    branches:
      - dev # Chỉ kích hoạt khi push lên nhánh dev

jobs:
  notify-team:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Send email notification
        run: |
          echo "Sending email notifications to team members..."